version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    target-branch: "main"
    groups:
      uv-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    target-branch: "main"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    target-branch: "main"
    groups:
      docker-dependencies:
        patterns:
          - "*"
